# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: ocr-indexer
description: Indexer for AssetContract registry and Asset subscriptions

contracts:
  - name: AssetRegistry
    abi_file_path: ./abis/AssetRegistry.json
    handler: ./src/EventHandlers.ts
    events:
      - event: AssetCreated(bytes32 indexed assetId, address indexed asset, uint256 subscriptionPrice, address tokenAddress, address indexed owner)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: CreatorFeeShareUpdated(uint256 newCreatorFeeShare)
      - event: RegistryFeeShareUpdated(uint256 newRegistryFeeShare)

  - name: Asset
    abi_file_path: ./abis/Asset.json
    handler: ./src/EventHandlers.ts
    events:
      - event: SubscriptionAdded(address indexed user, uint256 indexed startTime, uint256 indexed endTime, uint256 nonce)
      - event: SubscriptionPriceUpdated(uint256 newSubscriptionPrice)
      - event: SubscriptionRevoked(address indexed user)
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)

networks:
  # Sepolia
  - id: 11155111
    start_block: 10299077
    rpc_config:
      url: https://rpc.sepolia.org
    contracts:
      - name: AssetRegistry
        address:
          - "0x513972072Ae1985506e2FC3b3d9A46fe0F0eCDB5" 
      - name: Asset
        address:
          - "0xca6f6d53ec05bbfd0a1888b777ea729549f66454"
          - "0xcdd88d9f65a79de88b512dd72276620ea0641aad"
          - "0xffb9bf5c3e811288c5b63acffaa8fd9a0f705227"
          - "0xc01ca58aebdf0ae085b9f229dc4b25d4386e3504"
          - "0x427a32acc5a1ebf3956df80d454c1184814170cf"
          - "0x043887c55b378bead8cda17b1498fca5146f7e2e"
          - "0x5b0c3f7c3bd95efdbf913c50be935c9ab969fcd1"
          - "0x827a062637c52be85c3e7b79fd171d3ac21b9bad"

  # For local testing, see readme
  # - id: 31337 # Anvil local network
  #   start_block: 0
  #   rpc_config:
  #     url: https://gateway.tenderly.co/public/sepolia
  #   contracts:
  #     - name: AssetRegistry
  #       address:
  #         - "0x93759d1Db2587FE353e010E8cF90a22377AE9E3b" 
  #     - name: Asset
  #       address:
  #         - "0x31c2823a3D9Bed91F5ae62F3F3D674A0Bf36b795"

unordered_multichain_mode: true
preload_handlers: true
address_format: lowercase